Experiments with tensor shapes and sizes

In [1]:
#Experiments

import torch
import torch.nn as nn
import torch.nn.functional as F

x_input = torch.linspace(-100,100,20)
print(x_input)

tensor([-100.0000,  -89.4737,  -78.9474,  -68.4211,  -57.8947,  -47.3684,
         -36.8421,  -26.3158,  -15.7895,   -5.2632,    5.2632,   15.7895,
          26.3158,   36.8421,   47.3684,   57.8947,   68.4211,   78.9474,
          89.4737,  100.0000])


In [44]:
exponential = torch.exp(-x_input**2)
sine = torch.sin(x_input)
cosine = torch.cos(x_input)
box = torch.ones(20)

print(box)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])


# Why do we need to reshape the tensors box, cosine, sine, exponential for convolution? 

In [45]:
print(exponential.shape)
print(sine.shape)
print(cosine.shape)
print(box.shape)


torch.Size([20])
torch.Size([20])
torch.Size([20])
torch.Size([20])


In [46]:
signal_expo = exponential.view(1,1,-1)
print(signal_expo.shape)

kernal = box.view(1,1,-1)
print(kernal.shape)

conv_result = F.conv1d(signal_expo,kernal,padding=10)
print(conv_result)

torch.Size([1, 1, 20])
torch.Size([1, 1, 20])
tensor([[[9.3256e-13, 1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12,
          1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12,
          1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12,
          1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12,
          9.3256e-13]]])


In [63]:
box = torch.zeros(len(x_input))
box[-50:50] = 1
print(box.shape,box.size())
box_kernal = box.view(1,1,-1)
padd =5

conv_result2 = F.conv1d(signal_expo,box_kernal,padding=padd)
print(conv_result2.shape,conv_result2.size())

padd =4
conv_result3 = F.conv1d(signal_expo, box_kernal, padding=padd)
print("conv_result3 size =",conv_result3.size()," & conv_result3 shape =", conv_result3.shape)
print(conv_result3)

padd=3
conv_result4 = F.conv1d(signal_expo, box_kernal, padding=padd)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)


torch.Size([20]) torch.Size([20])
torch.Size([1, 1, 11]) torch.Size([1, 1, 11])
conv_result3 size = torch.Size([1, 1, 9])  & conv_result3 shape = torch.Size([1, 1, 9])
tensor([[[1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12,
          1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12]]])
conv_result4 size = torch.Size([1, 1, 7])  & conv_result4 shape = torch.Size([1, 1, 7])
tensor([[[1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12,
          1.8651e-12, 1.8651e-12]]])


In [65]:
stride=5
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=3
print(stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=2
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=1
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

conv_result4 size = torch.Size([1, 1, 1])  & conv_result4 shape = torch.Size([1, 1, 1])
tensor([[[1.8651e-12]]])
3
conv_result4 size = torch.Size([1, 1, 1])  & conv_result4 shape = torch.Size([1, 1, 1])
tensor([[[1.8651e-12]]])

 2
conv_result4 size = torch.Size([1, 1, 1])  & conv_result4 shape = torch.Size([1, 1, 1])
tensor([[[1.8651e-12]]])

 1
conv_result4 size = torch.Size([1, 1, 1])  & conv_result4 shape = torch.Size([1, 1, 1])
tensor([[[1.8651e-12]]])


In [66]:
stride=5
padding = 3
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=3
padding = 3
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=2
padding = 3
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=1
padding = 3
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)


 5
conv_result4 size = torch.Size([1, 1, 2])  & conv_result4 shape = torch.Size([1, 1, 2])
tensor([[[1.8651e-12, 1.8651e-12]]])

 3
conv_result4 size = torch.Size([1, 1, 3])  & conv_result4 shape = torch.Size([1, 1, 3])
tensor([[[1.8651e-12, 1.8651e-12, 1.8651e-12]]])

 2
conv_result4 size = torch.Size([1, 1, 4])  & conv_result4 shape = torch.Size([1, 1, 4])
tensor([[[1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12]]])

 1
conv_result4 size = torch.Size([1, 1, 7])  & conv_result4 shape = torch.Size([1, 1, 7])
tensor([[[1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12, 1.8651e-12,
          1.8651e-12, 1.8651e-12]]])


In [67]:
stride=1
padding = 100
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=1
padding = 50
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=1
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=3
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=4
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=5
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)


 1
conv_result4 size = torch.Size([1, 1, 201])  & conv_result4 shape = torch.Size([1, 1, 201])
tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000

In [75]:
box = torch.ones(len(x_input))

box_kernal = box.view(1,1,-1)
stride=1
padding = 100
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=1
padding = 50
print("\n",stride)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=1
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=3
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=4
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)

stride=5
padding = 25
print("\n",stride)
print("\n",padding)
conv_result4 = F.conv1d(signal_expo, box_kernal, stride=stride, padding=padding)
print("conv_result4 size =",conv_result4.size()," & conv_result4 shape =", conv_result4.shape)
print(conv_result4)


 1
conv_result4 size = torch.Size([1, 1, 201])  & conv_result4 shape = torch.Size([1, 1, 201])
tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000

In [88]:
# Simple example
signal = torch.tensor([1.0, 2, 3, 4, 5]).view(1,1,-1)
kernel = torch.ones(1,1,3) / 3  # Average 3 values

print(signal)
print(kernel)
# No padding, stride=1
out = F.conv1d(signal, kernel, padding=0, stride=1)
print(out)  # [2.0, 3.0, 4.0] = averages of [1,2,3], [2,3,4], [3,4,5]

# Padding=1, stride=1
out = F.conv1d(signal, kernel, padding=1, stride=1)
print(out)  # [1.0, 2.0, 3.0, 4.0, 5.0] = same length as input!

# No padding, stride=2
out = F.conv1d(signal, kernel, padding=0, stride=2)
print(out)  # [2.0, 4.0] = only 2 outputs (skipped positions)

tensor([[[1., 2., 3., 4., 5.]]])
tensor([[[0.3333, 0.3333, 0.3333]]])
tensor([[[2., 3., 4.]]])
tensor([[[1., 2., 3., 4., 3.]]])
tensor([[[2., 4.]]])


In [89]:
print(kernel)
print(len(kernel))
print(kernel.size())
print(kernel.shape)

tensor([[[0.3333, 0.3333, 0.3333]]])
1
torch.Size([1, 1, 3])
torch.Size([1, 1, 3])


In [ ]:
tensor_1 = torch.ones(1,1,3)
tensor_2 = torch.ones(1,1,5)


print(tensor_1)
print(tensor_2)

tensor([[[1., 1., 1.]]])
tensor([[[1., 1., 1., 1., 1.]]])


In [99]:
tensor_3 = torch.tensor([1.0,2,3,4,5,6]).view(1,1,-1)
tensor_4 = torch.ones(1,1,3)/3
out_3_4 = F.conv1d(tensor_3, tensor_4, padding=0, stride=1)
print(tensor_3,'\n',tensor_4,'\n',out_3_4)


tensor([[[1., 2., 3., 4., 5., 6.]]]) 
 tensor([[[0.3333, 0.3333, 0.3333]]]) 
 tensor([[[2., 3., 4., 5.]]])


In [108]:
tensor_3 = torch.tensor([1.0,2,3,4,5,6]).view(1,1,-1)
tensor_4 = torch.ones(1,1,3)/3
out_3_4 = F.conv1d(tensor_3, tensor_4, padding=1, stride=3)
print(tensor_3,'\n',tensor_4,'\n',out_3_4)


tensor([[[1., 2., 3., 4., 5., 6.]]]) 
 tensor([[[0.3333, 0.3333, 0.3333]]]) 
 tensor([[[1., 4.]]])


In [115]:
# Simple example
signal = torch.tensor([1.0, 2, 3, 4, 5]).view(1,1,-1)
kernel = torch.ones(1,1,3)/2 # Average 3 values

# No padding, stride=1
print(signal,"\n")
print(kernel,"\n")
out = F.conv1d(signal, kernel, padding=0, stride=1)
print(out)  # [2.0, 3.0, 4.0] = averages of [1,2,3], [2,3,4], [3,4,5]

out = F.conv1d(signal, kernel, padding=0, stride=2)
print(out)  

out = F.conv1d(signal, kernel, padding=0, stride=3)
print(out)  

# Padding=1, stride=1
out = F.conv1d(signal, kernel, padding=1, stride=1)
print(out)  # [1.0, 2.0, 3.0, 4.0, 5.0] = same length as input!

# No padding, stride=2
out = F.conv1d(signal, kernel, padding=0, stride=2)
print(out)  # [2.0, 4.0] = only 2 outputs (skipped positions)

tensor([[[1., 2., 3., 4., 5.]]]) 

tensor([[[0.5000, 0.5000, 0.5000]]]) 

tensor([[[3.0000, 4.5000, 6.0000]]])
tensor([[[3., 6.]]])
tensor([[[3.]]])
tensor([[[1.5000, 3.0000, 4.5000, 6.0000, 4.5000]]])
tensor([[[3., 6.]]])
